# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2862d19f4792913b4e9bac89c391fe35f497a33adbf014e900a318cb331175fe5e92e18db83e3f8a82bb5ac994eac3e47f1d2e2dfb6c90b91f3e2032b3c0c776

test:
  secret_key_base: 38658a1b93d09a2cdf510e672607392b546dc0c9eea17b429a80f8e1b03af9696171e0dea20b9de741a9729fd5862ccc861045b1df9f80f1125a8e9920bbe890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
